name: branch_checkout
on: [push]
jobs:
  external-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout external repository
        uses: actions/checkout@v3
        with:
          repository: abystoma/external-workflow
          ref: branch
      - name: Greetings
        run: echo "$(<greetings.txt)"
